/// Flutter icons HarmonyNav1
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HarmonyNav1
///      fonts:
///       - asset: fonts/HarmonyNav1.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HarmonyNav1 {
  HarmonyNav1._();

  static const _kFontFam = 'HarmonyNav1';
  static const String? _kFontPkg = null;

  static const IconData ic_public_more = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_public_history = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_public_home = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
